### ISSUE TITLE
Feature Request: Set Location, Langage List Manually

### ISSUE THREAD

**Issue by aubergemediale** [pragmatrix/Dominator#1]
It would be useful if the user could simulate residing in a different geolocation (so that search engines adjust their results respectively. Same with languages.

Maybe this could be a starting point:
https://msdn.microsoft.com/en-us/library/windows/hardware/hh768273(v=vs.85).aspx

**Comment by pragmatrix** [comment]
Interesting suggestion, but this is out of scope for this project. I'm sure there are other tools that are able to change the geolocation.
