### ISSUE TITLE
meaning of green No! and red Yes button.

### ISSUE THREAD

**Issue by AdKiller** [pragmatrix/Dominator#6]
Sorry for the stupid question, but I am not sure what is meant by the green NO and red YES.

For example in the following screen, is it currently allowing PC to connect to Microsoft telemetry servers or not?

![untitled](https://user-images.githubusercontent.com/13304436/30336522-b64a9f08-97e5-11e7-9a1e-5e9b81af5716.jpg)

I use ShutUp10 and WPD and WindowsSpyBlocker to fully block Microsoft spywares (hopefully).

**Comment by pragmatrix** [comment]
Interesting, and thank you for asking, I would never have thought that this leads to confusion.

It answer the line above, so for example "Yes" is the answer to the question "Allow this PC to connect to Microsoft telemetry servers.".  

Green is always the better option as seen from a privacy protecting perspective, Red is the worse one or the system default setting. 

I guess adding a question mark to the individual setting's title would be beneficial?

If you have an idea how the visual feedback can be further improved, I would very much appreciate it.

**Comment by pragmatrix** [comment]
cc @mk0815

**Comment by AdKiller** [comment]
sorry I guess the confusion was because I was not expecting the app to say that I was connecting to telemetry because I had already blocked everything with ShutUp10 and WPD and WindowsSpyBlocker. 

and because I thought it means swipe right to make it yes.  Maybe removing yes and no from inside the switches would be a better option. 

Thanks

**Comment by pragmatrix** [comment]
I understand. There are different methods to stop the telemetry collection, one is to disable it via the registry, which AFAIK works only partially, and the other is to block the telemetry servers in the `hosts.txt` file which Dominator also supports.

@mk0815 and I talked about the problem and also thought about removing the buttons, but then decided that adding question marks are sufficient. I'll close this issue now. The next release will add the question marks to the titles (see #7). 

And thank you for the feedback.

**Comment by mk0815** [comment]
Message from the past ;)

if "No/green" and "yes/red" cause
